on:
  schedule:
    # runs every day at 7:00 AM UTC = 3AM ET in jan, feb, sep-dec
    - cron:  '0 7 * 1,2,9-12 *'
  workflow_dispatch:

name: update_ngs

jobs:
  update:
    name: update data
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.NFLVERSE_GH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install necessary packages
        run: |
          install.packages(c("dplyr", "purrr", "readr", "cli", "httr", "janitor", "callr", "rvest", "qs", "arrow", "remotes"), type = "binary")
          remotes::install_github("nflverse/nflverse-data")
        shell: Rscript {0}
      - name: Run ngs update script
        run: Rscript -e 'source("R/update_ngs.R")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add data
          git commit -m "NGS data updated `date`" || echo "No changes to commit"
          git push origin main || echo "No changes to commit"
