on:
  schedule:
    # runs every day at 7:00 AM UTC = 3AM ET in jan, feb, sep-dec
    - cron:  '0 7 * 1,2,9-12 *'
  workflow_dispatch:
    inputs:
      full_rebuild:
        description: 'Full Rebuild'
        required: true
        default: false
        type: boolean

name: update_ngs

jobs:
  update:
    name: update data
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.NFLVERSE_GH_TOKEN }}
      GH_TOKEN: ${{ secrets.NFLVERSE_GH_TOKEN }}
      NFLVERSE_REBUILD: ${{ inputs.full_rebuild }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 3
          extra-packages: |
            nflverse/nflverse-data
      - name: Run ngs update script
        run: Rscript -e 'source("R/update_ngs.R")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add data
          git commit -m "NGS data updated `date`" || echo "No changes to commit"
          git push origin main || echo "No changes to commit"
