on:
  schedule:
    # runs every day at 7:00 AM UTC = 3AM ET in jan, feb, sep-dec
    - cron:  '0 7 * 1,2,9-12 *'
  workflow_dispatch:
    inputs:
      season_rebuild:
        description: 'Rebuild Season (9999 defaults to latest season)'
        required: false
        default: 9999
        type: number
      full_rebuild:
        description: 'Full Rebuild (overwrites above season)'
        required: true
        default: false
        type: boolean

name: Update NGS Data

jobs:
  ngs_setup:
    runs-on: ubuntu-latest
    name: ngs_setup
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FULL_REBUILD: ${{ inputs.full_rebuild || false }}
      SEASON_REBUILD: ${{ inputs.season_rebuild || 9999 }}
    outputs:
      seasons: ${{ steps.query_seasons.outputs.seasons }}
    steps:
      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: nflverse/nflverse-workflows

      - id: query_seasons
        name: Query Seasons
        run: |
          if [ $FULL_REBUILD == true ]
          then
            seasons=$( Rscript -e 'nflverse.workflows::get_season_range(2016)' )
          elif [ $SEASON_REBUILD == 9999 ]
          then
            seasons=$( Rscript -e 'nflverse.workflows::get_current_season()' )
          else
            seasons=${{ env.SEASON_REBUILD }}
          fi
          echo "seasons=$seasons" >> "$GITHUB_OUTPUT"

  update_ngs_seasons:
    needs: ngs_setup
    name: Update ${{ matrix.season }} ${{ matrix.type }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        season: ${{ fromJson(needs.ngs_setup.outputs.seasons) }}
        type: ["passing", "rushing", "receiving"]
    env:
      GH_TOKEN: ${{ secrets.NFLVERSE_GH_TOKEN }}
      NFLVERSE_UPDATE_SEASON: ${{ matrix.season }}
      NFLVERSE_UPDATE_TYPE: ${{ matrix.type }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          extra-repositories: 'https://nflverse.r-universe.dev'
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            dplyr,
            purrr,
            cli,
            httr,
            janitor,
            rvest,
            rlang,
            glue,
            nflreadr
          extra-packages: nflverse/nflverse-data
      - name: Release ${{ matrix.type }}
        run: Rscript -e 'source("R/update_ngs.R")'

  combine_stats:
    needs: [ngs_setup, update_ngs_seasons]
    name: Combine NGS Season Data
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        type: ["combine"]
    env:
      GH_TOKEN: ${{ secrets.NFLVERSE_GH_TOKEN }}
      NFLVERSE_UPDATE_TYPE: ${{ matrix.type }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          extra-repositories: 'https://nflverse.r-universe.dev'
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            cli,
            glue,
            nflreadr,
            purrr
          extra-packages: nflverse/nflverse-data
      - name: Release Combined NGS Data
        run: Rscript -e 'source("R/update_ngs.R")'
